#!/usr/bin/env ansible-playbook
---
- name: configures vim
  hosts: localhost
  connection: local
  tasks:
    - name: install apt packages
      action: apt pkg={{ item }} state=present
      become: yes
      with_items:
        - fd-find
        - cmake
        - exuberant-ctags
        - git
        - python-dev
        - ripgrep
        - rsync

        # Dependencies for apt_repository
        - python-apt
        - python-pycurl

        - neovim
        - python3-neovim
      when: no_sudo is not defined
