version: 2
root-markers:
  - .git/
  - _darcs/
  - .hg/
  - .bzr/
  - .svn/

tools:
  dprint: &dprint
    format-stdin: true
    format-command: "dprint fmt --stdin ${INPUT}"
    root-markers:
      - dprint.json
      - .dprint.json
    require-marker: true

  lua-format: &lua-format
    format-sdin: true
    format-command: "lua-format"

  prettier: &prettier
    format-stdin: true
    format-command: "prettier --stdin-filepath ${INPUT}"
    root-markers:
      - .prettierrc
      - .prettierrc.json
      - .prettierrc.yaml
      - .prettierrc.yml
      - .prettierrc.json5
      - .prettierrc.js
      - .prettierrc.cjs
      - .prettierrc.toml
      - prettierrc.config.js
      - prettierrc.config.cjs
    require-marker: true

  rustfmt: &rustfmt
    format-stdin: true
    format-command: "rustfmt"

languages:
  javascript:
    - <<: *dprint
    - <<: *prettier

  json:
    - <<: *dprint
    - <<: *prettier

  lua:
    - <<: *lua-format

  typescript:
    - <<: *dprint
    - <<: *prettier

  rust:
    - <<: *rustfmt

  yaml:
    - <<: *prettier
